name: PlayerLastQuit
version: '${project.version}'
main: cn.paper_card.player_last_quit.PlayerLastQuit
api-version: 1.20
author: Paper99
folia-supported: true

depend:
  - Database

commands:
  player-last-quit:
    permission: player-last-quit.command

permissions:
  player-last-quit.command:
    default: op
